{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
  annotations:
    # Annotation for OCI workload identity
    oci.oraclecloud.com/workload-identity: "true"
{{- end }} 