# backend-updater-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "corrino-lens.fullname" . }}-backend-updater
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps","services","pods"]
    verbs: ["get","list","watch","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","patch","update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "corrino-lens.fullname" . }}-backend-updater
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backend.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "corrino-lens.fullname" . }}-backend-updater