kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "corrino-lens.fullname" . }}-backend-clusterrole
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "pods", "nodes", "namespaces" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses", "networkpolicies" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]
    verbs: [ "get", "list", "watch" ]
  # Additional permissions for terminate-node functionality
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/eviction" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "patch", "update" ]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    verbs: [ "get", "list", "watch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets" ]
    verbs: [ "get", "list", "watch", "delete" ]
  - apiGroups: ["batch"]     
    resources: ["jobs"]     
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "corrino-lens.fullname" . }}-backend-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backend.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "corrino-lens.fullname" . }}-backend-clusterrole
  apiGroup: rbac.authorization.k8s.io