apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corrino-lens.fullname" . }}-frontend-configmap
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
data:
  API_BASE_URL: "http://{{ include "corrino-lens.fullname" . }}-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.servicePort }}"