apiVersion: v1
kind: Service
metadata:
  name: {{ include "corrino-lens.fullname" . }}-frontend
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
        app: {{ include "corrino-lens.fullname" . }}-frontend
  ports:
    - name: lens-frontend
      protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}