apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.certManager.clusterIssuer }}"
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  defaultBackend:
    service:
      name: {{ include "corrino-lens.fullname" . }}-frontend
      port:
        number: 80
  rules: []  # Job will patch real rules later
  tls:
    - hosts: []  # Job will patch real hosts later
      secretName: {{ .Release.Name }}-frontend-tls
