{{- if .Values.grafana.enabled }}
{{- $secretName := "lens-grafana-secret" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ "admin" | b64enc | quote }}
  admin-password: {{ if $secret }}{{ index $secret.data "admin-password" }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
{{- end }}