apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corrino-lens.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
  annotations:
    # Create as pre-install hook to be available for other hook jobs
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-ingress-ip-discovery
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
  annotations:
    # Create as pre-install hook to be available for other hook jobs
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "secrets", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-ingress-ip-discovery
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
  annotations:
    # Create as pre-install hook to be available for other hook jobs
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-ingress-ip-discovery
subjects:
- kind: ServiceAccount
  name: {{ include "corrino-lens.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
