apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-patcher
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-patcher-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]  
    verbs: ["get", "patch", "update"]
---
# ClusterRole for accessing ingress-nginx services
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-patcher-cluster-role
  annotations:
    "helm.sh/hook": post-install,post-upgrade
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "patch", "update"]
    {{- if index .Values "ingress-nginx" "enabled" }}
    resourceNames: ["{{ .Release.Name }}-ingress-nginx-controller"]
    {{- else }}
    resourceNames: ["{{ .Values.ingress.external.serviceName }}"]
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-patcher-cluster-binding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-patcher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-patcher-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-patcher-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-patcher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-patcher-role
  apiGroup: rbac.authorization.k8s.io
