apiVersion: v1
kind: Service
metadata:
  name: {{ include "corrino-lens.fullname" . }}-postgres-lb
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "corrino-lens.fullname" . }}-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.database.servicePort }}
      targetPort: {{ .Values.database.servicePort }}
