apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corrino-lens.fullname" . }}-postgres-secret
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.global.postgresDb | quote }}