{{- if not .Values.backend.prometheusUrl }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-prometheus-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corrino-lens.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.certManager.clusterIssuer }}"
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  defaultBackend:
    service:
      name: {{ .Values.monitoring.prometheusService }}
      port:
        number: {{ .Values.monitoring.prometheusPort }}
  rules: []  # Job will patch real rules later
  tls:
    - hosts: []  # Job will patch real hosts later
      secretName: {{ .Release.Name }}-prometheus-tls
{{- end }}
